import { beforeAll, beforeEach, afterAll, describe, expect, it } from "vitest";
import request from "supertest";
import { PrismaClient } from "@prisma/client";
const url = process.env.TEST_DATABASE_URL;
const tag = `clinic-test-${Date.now()}`;
describe.skipIf(!url)("Clinic ownership, invitations and shared subscriptions (local PostgreSQL)", () => {
  let db: PrismaClient; let app: ReturnType<typeof import("../../src/app").createApp>;
  let sign: typeof import("../../src/utils/jwt").signAccessToken;
  let location: { wilayaId: string; cityId: string }; let specialtyId: string; let adminToken: string;
  let serial = 0; const owners: string[] = [];
  const email = () => `user-${serial++}.${tag}@example.test`;
  const bearer = (token: string) => ({ Authorization: `Bearer ${token}` });
  const clinicProfile = () => ({ nameAr: `عيادة ${tag}`, address: "شارع الاختبار المحلي", ...location });
  const doctorProfile = () => ({ firstName: "أمين", lastName: `اختبار-${serial++}`, specialtyId });
  async function owner(practises = true) {
    const response = await request(app).post("/api/auth/register/clinic").send({ email: email(), password: "ClinicTest123!", clinic: clinicProfile(), ...(practises ? { doctor: doctorProfile() } : {}) });
    expect(response.status).toBe(201); expect(response.body.data.user.passwordHash).toBeUndefined();
    const user = response.body.data.user; owners.push(user.id);
    return { user, clinicId: user.ownedClinic.id as string, token: response.body.data.accessToken as string };
  }
  async function invite(token: string, targetEmail = email()) {
    const response = await request(app).post("/api/clinics/mine/invites").set(bearer(token)).send({ email: targetEmail });
    expect(response.status).toBe(201); expect(response.body.data.invite.tokenHash).toBeUndefined();
    return response.body.data.rawToken as string;
  }
  const accept = (token: string) => request(app).post("/api/auth/register/clinic-doctor").send({ token, password: "ClinicTest123!", doctor: doctorProfile() });
  beforeAll(async () => {
    const parsed = new URL(url!);
    if (!["127.0.0.1", "localhost", "[::1]"].includes(parsed.hostname) || !["/medbook_clinic_test", "/medbook_clinic_test_v2", "/medbook_security_test"].includes(parsed.pathname)) throw new Error("Only explicitly named isolated loopback test databases are allowed");
    process.env.DATABASE_URL = url!; process.env.RATE_LIMIT_MAX = "1000000"; process.env.NODE_ENV = "test";
    process.env.BUDGETSMS_USERNAME = ""; process.env.BUDGETSMS_USERID = ""; process.env.BUDGETSMS_HANDLE = "";
    process.env.VAPID_PUBLIC_KEY = ""; process.env.VAPID_PRIVATE_KEY = "";
    db = new PrismaClient({ datasourceUrl: url });
    const wilaya = await db.wilaya.create({ data: { code: tag.slice(-6), nameAr: tag } });
    const city = await db.city.create({ data: { nameAr: tag, wilayaId: wilaya.id } });
    const specialty = await db.specialty.create({ data: { nameAr: tag } });
    location = { wilayaId: wilaya.id, cityId: city.id }; specialtyId = specialty.id;
    ({ signAccessToken: sign } = await import("../../src/utils/jwt"));
    const admin = await db.user.create({ data: { email: email(), passwordHash: "unused-test-only", role: "ADMIN" } });
    adminToken = sign({ sub: admin.id, role: "ADMIN" });
    app = (await import("../../src/app")).createApp();
  }, 60000);
  beforeEach(async () => {
    // Each scenario gets an independent auth budget; production limits remain unchanged.
    const { authLimiter } = await import("../../src/middleware/rateLimiter");
    for (const address of ["127.0.0.1", "::ffff:127.0.0.1", "::1"]) {
      authLimiter.resetKey(address);
    }
  });
  afterAll(async () => {
    if (!db || !location) return;
    await db.auditLog.deleteMany({ where: { user: { email: { endsWith: `.${tag}@example.test` } } } });
    await db.doctorReferral.deleteMany({ where: { rewardClinic: { ownerId: { in: owners } } } });
    await db.clinic.deleteMany({ where: { ownerId: { in: owners } } });
    await db.appointment.deleteMany({ where: { doctor: { user: { email: { endsWith: `.${tag}@example.test` } } } } });
    await db.user.deleteMany({ where: { email: { endsWith: `.${tag}@example.test` } } });
    await db.specialty.delete({ where: { id: specialtyId } });
    await db.city.delete({ where: { id: location.cityId } });
    await db.wilaya.delete({ where: { id: location.wilayaId } });
    await db.$disconnect();
    const { prisma } = await import("../../src/lib/prisma"); await prisma.$disconnect();
  });
  it("credits clinic referrals once, preserves capacity and serializes multiple rewards", async () => {
    const a = await owner(); const b = await owner(); const c = await owner();
    const now = new Date();
    await db.clinic.update({ where: { id: a.clinicId }, data: { verificationStatus: "VERIFIED", subscriptionStatus: "ACTIVE", paidDoctorCount: 4, subscriptionExpiresAt: new Date(now.getTime() + 120 * 86400000) } });
    const before = await db.doctor.findUniqueOrThrow({ where: { id: a.user.doctor.id } });
    for (const referred of [b, c]) await db.doctorReferral.create({ data: { referrerDoctorId: a.user.doctor.id, referredDoctorId: referred.user.doctor.id, referralCodeUsed: "clinic-test" } });
    const { grantReferralRewardTx } = await import("../../src/modules/referrals/referrals.service");
    const grant = (id: string) => db.$transaction(tx => grantReferralRewardTx(tx, id, null, now));
    const results = await Promise.all([grant(b.user.doctor.id), grant(b.user.doctor.id), grant(c.user.doctor.id)]);
    expect(results.filter(Boolean)).toHaveLength(2);
    const clinic = await db.clinic.findUniqueOrThrow({ where: { id: a.clinicId } });
    expect(clinic.paidDoctorCount).toBe(4);
    expect(clinic.referralDiscountUntil!.getTime() - now.getTime()).toBe(60 * 86400000);
    expect(clinic.subscriptionExpiresAt!.getTime()).toBe(now.getTime() + 120 * 86400000);
    const after = await db.doctor.findUniqueOrThrow({ where: { id: before.id } });
    expect(after.subscriptionStatus).toBe(before.subscriptionStatus);
    expect(after.subscriptionExpiresAt).toEqual(before.subscriptionExpiresAt);
    const referral = await db.doctorReferral.findUniqueOrThrow({ where: { referredDoctorId: b.user.doctor.id } });
    expect(referral.rewardClinicId).toBe(a.clinicId);
    const { clinicReferralBilling } = await import("../../src/lib/clinicReferralReward");
    expect(clinicReferralBilling(4, clinic.referralDiscountUntil, now)).toMatchObject({ billedDoctorCount: 3, monthlyTotal: 12000 });
  });
  it("rolls back the clinic discount together with referral status when the transaction fails", async () => {
    const a = await owner(); const b = await owner();
    await db.doctorReferral.create({ data: { referrerDoctorId: a.user.doctor.id, referredDoctorId: b.user.doctor.id, referralCodeUsed: "clinic-rollback" } });
    const { grantReferralRewardTx } = await import("../../src/modules/referrals/referrals.service");
    await expect(db.$transaction(async tx => {
      await grantReferralRewardTx(tx, b.user.doctor.id, null);
      throw new Error("rollback-reward");
    })).rejects.toThrow("rollback-reward");
    const clinic = await db.clinic.findUniqueOrThrow({ where: { id: a.clinicId } });
    const referral = await db.doctorReferral.findUniqueOrThrow({ where: { referredDoctorId: b.user.doctor.id } });
    expect(clinic.pendingReferralDays).toBe(0); expect(clinic.referralDiscountUntil).toBeNull();
    expect(referral.status).toBe("PENDING"); expect(referral.rewardClinicId).toBeNull();
  });
  it("keeps an inactive clinic reward pending until an admin activates its subscription", async () => {
    const a = await owner(); const b = await owner();
    await db.doctorReferral.create({ data: { referrerDoctorId: a.user.doctor.id, referredDoctorId: b.user.doctor.id, referralCodeUsed: "clinic-pending" } });
    const { grantReferralRewardTx } = await import("../../src/modules/referrals/referrals.service");
    await db.$transaction(tx => grantReferralRewardTx(tx, b.user.doctor.id, null));
    const pending = await db.clinic.findUniqueOrThrow({ where: { id: a.clinicId } });
    expect(pending.pendingReferralDays).toBe(30); expect(pending.referralDiscountUntil).toBeNull();
    const activate = { verificationStatus: "VERIFIED", subscriptionStatus: "ACTIVE", paidDoctorCount: 1, subscriptionExpiresAt: new Date(Date.now() + 60 * 86400000) };
    expect((await request(app).patch(`/api/clinics/admin/${a.clinicId}`).set(bearer(adminToken)).send(activate)).status).toBe(200);
    const activated = await db.clinic.findUniqueOrThrow({ where: { id: a.clinicId } });
    expect(activated.pendingReferralDays).toBe(0); expect(activated.referralDiscountUntil!.getTime()).toBeGreaterThan(Date.now());
    const end = activated.referralDiscountUntil!.getTime();
    expect((await request(app).patch(`/api/clinics/admin/${a.clinicId}`).set(bearer(adminToken)).send(activate)).status).toBe(200);
    expect((await db.clinic.findUniqueOrThrow({ where: { id: a.clinicId } })).referralDiscountUntil!.getTime()).toBe(end);
    const mine = await request(app).get("/api/clinics/mine").set(bearer(a.token));
    expect(mine.body.data.billing).toMatchObject({ doctorCount: 1, billedDoctorCount: 0, monthlyTotal: 0, paidDoctorCount: 1 });
  });
  it("announces a clinic doctor when the clinic activates, with its name, once per patient", async () => {
    const o = await owner();
    const patient = await db.user.create({ data: { email: email(), passwordHash: "unused-test-only", role: "PATIENT", patient: { create: { firstName: "مريض", lastName: "الإعلان", cityId: location.cityId } } } });
    expect((await request(app).patch(`/api/admin/doctors/${o.user.doctor.id}/verify`).set(bearer(adminToken)).send({ status: "VERIFIED" })).status).toBe(200);
    const before = await db.notification.count({ where: { userId: patient.id, type: "NEW_DOCTOR_IN_AREA", newDoctorId: o.user.doctor.id } });
    expect(before).toBe(0);
    const active = { verificationStatus: "VERIFIED", subscriptionStatus: "ACTIVE", paidDoctorCount: 1, subscriptionExpiresAt: new Date(Date.now() + 60 * 86400000) };
    expect((await request(app).patch(`/api/clinics/admin/${o.clinicId}`).set(bearer(adminToken)).send(active)).status).toBe(200);
    const notifications = await db.notification.findMany({ where: { userId: patient.id, type: "NEW_DOCTOR_IN_AREA", newDoctorId: o.user.doctor.id } });
    expect(notifications).toHaveLength(1);
    const clinic = await db.clinic.findUniqueOrThrow({ where: { id: o.clinicId } });
    expect(notifications[0].message).toContain(clinic.nameAr);
    expect(notifications[0].title).toContain("تابع لعيادة");
    expect((await request(app).patch(`/api/clinics/admin/${o.clinicId}`).set(bearer(adminToken)).send(active)).status).toBe(200);
    expect(await db.notification.count({ where: { userId: patient.id, type: "NEW_DOCTOR_IN_AREA", newDoctorId: o.user.doctor.id } })).toBe(1);
  });
  it("announces a newly approved doctor in an already active clinic with the clinic name", async () => {
    const o = await owner();
    const patient = await db.user.create({ data: { email: email(), passwordHash: "unused-test-only", role: "PATIENT", patient: { create: { firstName: "مريض", lastName: "الموافقة", cityId: location.cityId } } } });
    const active = { verificationStatus: "VERIFIED", subscriptionStatus: "ACTIVE", paidDoctorCount: 1, subscriptionExpiresAt: new Date(Date.now() + 60 * 86400000) };
    expect((await request(app).patch(`/api/clinics/admin/${o.clinicId}`).set(bearer(adminToken)).send(active)).status).toBe(200);
    expect(await db.notification.count({ where: { userId: patient.id, type: "NEW_DOCTOR_IN_AREA", newDoctorId: o.user.doctor.id } })).toBe(0);
    expect((await request(app).patch(`/api/admin/doctors/${o.user.doctor.id}/verify`).set(bearer(adminToken)).send({ status: "VERIFIED" })).status).toBe(200);
    const notification = await db.notification.findFirstOrThrow({ where: { userId: patient.id, type: "NEW_DOCTOR_IN_AREA", newDoctorId: o.user.doctor.id } });
    const clinic = await db.clinic.findUniqueOrThrow({ where: { id: o.clinicId } });
    expect(notification.message).toContain(clinic.nameAr);
    expect(notification.title).toContain("تابع لعيادة");
  });
  it("uses one account and counts a practising owner once", async () => {
    const o = await owner(); expect(o.user.role).toBe("DOCTOR");
    const response = await request(app).get("/api/clinics/mine").set(bearer(o.token));
    expect(response.body.data.billing).toMatchObject({ doctorCount: 1, monthlyTotal: 4000 });
    expect(response.body.data.doctors[0].id).toBe(o.user.doctor.id);
  });
  it("does not bill an owner who only manages the clinic", async () => {
    const o = await owner(false); expect(o.user.role).toBe("CLINIC_OWNER"); expect(o.user.doctor).toBeNull();
    const response = await request(app).get("/api/clinics/mine").set(bearer(o.token));
    expect(response.body.data.billing.monthlyTotal).toBe(0);
  });
  it("enforces owner and admin isolation and rejects self-activation", async () => {
    const a = await owner(); const b = await owner();
    expect((await request(app).get(`/api/clinics/mine/doctors/${b.user.doctor.id}/assistants`).set(bearer(a.token))).status).toBe(404);
    expect((await request(app).get("/api/clinics/admin/list").set(bearer(a.token))).status).toBe(403);
    expect((await request(app).get("/api/clinics/mine")).status).toBe(401);
    expect((await request(app).patch("/api/clinics/mine").set(bearer(a.token)).send({ ...clinicProfile(), subscriptionStatus: "ACTIVE" })).status).toBe(400);
    const assistant = sign({ sub: a.user.id, role: "ASSISTANT" });
    expect((await request(app).get("/api/clinics/mine").set(bearer(assistant))).status).toBe(403);
  });
  it("prevents selecting a clinic through independent registration", async () => {
    const o = await owner();
    const response = await request(app).post("/api/auth/register/doctor").send({ email: email(), password: "ClinicTest123!", ...doctorProfile(), ...location, clinicId: o.clinicId });
    expect(response.status).toBe(403);
  });
  it("consumes each invitation once under concurrent acceptance", async () => {
    const o = await owner(); const token = await invite(o.token);
    const responses = await Promise.all([accept(token), accept(token)]);
    expect(responses.filter(r => r.status === 201)).toHaveLength(1);
    expect(responses.every(r => [201, 400, 409].includes(r.status))).toBe(true);
    expect(await db.doctor.count({ where: { clinicId: o.clinicId } })).toBe(2);
    const stored = await db.clinicDoctorInvite.findFirst({ where: { clinicId: o.clinicId } });
    expect(stored?.tokenHash).not.toBe(token); expect(stored?.status).toBe("ACCEPTED");
  });
  it("blocks cancelled invitations and invalid paid subscription activation", async () => {
    const o = await owner(); const token = await invite(o.token);
    const row = await db.clinicDoctorInvite.findFirstOrThrow({ where: { clinicId: o.clinicId } });
    expect((await request(app).delete(`/api/clinics/mine/invites/${row.id}`).set(bearer(o.token))).status).toBe(200);
    expect((await accept(token)).status).toBe(400);
    expect((await request(app).patch(`/api/clinics/admin/${o.clinicId}`).set(bearer(adminToken)).send({ subscriptionStatus: "ACTIVE", paidDoctorCount: 0, subscriptionExpiresAt: new Date(Date.now() + 86400000) })).status).toBe(400);
  });
  it("keeps a paid doctor's clinic unavailable until the clinic is reviewed and paid", async () => {
    const o = await owner(); const id = o.user.doctor.id;
    await db.doctor.update({ where: { id }, data: { verificationStatus: "VERIFIED", subscriptionStatus: "ACTIVE" } });
    expect((await request(app).get(`/api/doctors/${id}`)).status).toBe(404);
    const active = { verificationStatus: "VERIFIED", subscriptionStatus: "ACTIVE", paidDoctorCount: 1, subscriptionExpiresAt: new Date(Date.now() + 86400000) };
    expect((await request(app).patch(`/api/clinics/admin/${o.clinicId}`).set(bearer(adminToken)).send(active)).status).toBe(200);
    const visible = await request(app).get(`/api/clinics/${o.clinicId}`);
    expect(visible.status).toBe(200); expect(visible.body.data.doctors).toHaveLength(1);
    expect(visible.body.data.ownerId).toBeUndefined(); expect(visible.body.data.subscriptionStatus).toBeUndefined();
    expect((await request(app).get(`/api/doctors/${id}`)).status).toBe(200);
    const namedDoctor = await db.doctor.findUniqueOrThrow({ where: { id } });
    const byName = await request(app).get("/api/doctors").query({ q: `${namedDoctor.firstName} ${namedDoctor.lastName}` });
    expect(byName.status).toBe(200); expect(byName.body.data.items.some((d: { id: string }) => d.id === id)).toBe(true);
    await db.doctorSchedule.createMany({ data: Array.from({ length: 7 }, (_, dayOfWeek) => ({ doctorId: id, dayOfWeek, startTime: "08:00", endTime: "18:00" })) });
    expect((await request(app).get(`/api/booking/next-slot?doctorId=${id}`)).status).toBe(200);
    const patient = await db.user.create({ data: { email: email(), passwordHash: "unused-test-only", role: "PATIENT", patient: { create: { firstName: "مريض", lastName: "الاختبار" } } } });
    const patientToken = sign({ sub: patient.id, role: "PATIENT" });
    const booking = { firstName: "مريض", lastName: "الاختبار", wilayaId: location.wilayaId, specialtyId, doctorId: id };
    expect((await request(app).post("/api/booking").set(bearer(patientToken)).send(booking)).status).toBe(201);
    await db.clinic.update({ where: { id: o.clinicId }, data: { subscriptionExpiresAt: new Date(Date.now() - 1000) } });
    expect((await request(app).get(`/api/booking/next-slot?doctorId=${id}`)).status).toBe(404);
    expect((await request(app).get(`/api/doctors/${id}`)).status).toBe(404);
    expect((await request(app).get(`/api/clinics/${o.clinicId}`)).status).toBe(404);
    expect((await request(app).post("/api/booking").set(bearer(patientToken)).send(booking)).status).toBe(404);
  });
  it("does not exceed the paid capacity when different invites race", async () => {
    const o = await owner();
    await request(app).patch(`/api/clinics/admin/${o.clinicId}`).set(bearer(adminToken)).send({ subscriptionStatus: "ACTIVE", verificationStatus: "VERIFIED", paidDoctorCount: 2, subscriptionExpiresAt: new Date(Date.now() + 86400000) });
    const tokens = [await invite(o.token), await invite(o.token)];
    const responses = await Promise.all(tokens.map(t => accept(t)));
    expect(responses.map(r => r.status).sort()).toEqual([201, 409]);
    expect(await db.doctor.count({ where: { clinicId: o.clinicId } })).toBe(2);
    expect(await db.clinicDoctorInvite.count({ where: { clinicId: o.clinicId, status: "PENDING" } })).toBe(1);
  });
  it("joins an existing doctor directly once even when invitations from two clinics race", async () => {
    const a = await owner(false); const b = await owner(false); const targetEmail = email();
    const u = await db.user.create({ data: { email: targetEmail, passwordHash: "unused-test-only", role: "DOCTOR", doctor: { create: { ...doctorProfile(), ...location } } }, include: { doctor: true } });
    const tokens = [await invite(a.token, targetEmail), await invite(b.token, targetEmail)];
    const doctorToken = sign({ sub: u.id, role: "DOCTOR" });
    const responses = await Promise.all(tokens.map(token => request(app).post("/api/clinics/invites/accept").set(bearer(doctorToken)).send({ token })));
    expect(responses.map(r => r.status).sort()).toEqual([200, 409]);
    const joined = responses.find(r => r.status === 200)!.body.data;
    expect([a.clinicId, b.clinicId]).toContain(joined.clinicId);
    expect(joined.status).toBeUndefined();
    expect(await db.clinicTransferRequest.count({ where: { doctorId: u.doctor!.id } })).toBe(0);
    expect(await db.doctor.count({ where: { clinicId: { in: [a.clinicId, b.clinicId] } } })).toBe(1);
    expect(await db.clinicDoctorInvite.count({ where: { clinicId: { in: [a.clinicId, b.clinicId] }, status: "ACCEPTED" } })).toBe(1);
    expect(await db.auditLog.count({ where: { entityId: u.doctor!.id, action: "CLINIC_INVITE_ACCEPTED" } })).toBe(1);
    expect((await request(app).post("/api/clinics/invites/accept").set(bearer(doctorToken)).send({ token: tokens[responses.findIndex(r => r.status === 200)] })).status).toBe(400);
  });
  it("existing doctors cannot exceed paid capacity and the losing invitation remains usable", async () => {
    const o = await owner();
    await db.clinic.update({ where: { id: o.clinicId }, data: { subscriptionStatus: "ACTIVE", subscriptionExpiresAt: new Date(Date.now() + 86400000), paidDoctorCount: 2 } });
    const doctors = await Promise.all([0, 1].map(() => db.user.create({ data: { email: email(), passwordHash: "unchanged", role: "DOCTOR", doctor: { create: { ...doctorProfile(), ...location } } }, include: { doctor: true } })));
    const tokens = await Promise.all(doctors.map(d => invite(o.token, d.email)));
    const responses = await Promise.all(doctors.map((d, i) => request(app).post("/api/clinics/invites/accept").set(bearer(sign({ sub: d.id, role: "DOCTOR" }))).send({ token: tokens[i] })));
    expect(responses.map(r => r.status).sort()).toEqual([200, 409]);
    expect(await db.doctor.count({ where: { clinicId: o.clinicId } })).toBe(2);
    expect(await db.clinicDoctorInvite.count({ where: { clinicId: o.clinicId, status: "PENDING" } })).toBe(1);
    const loser = responses.findIndex(r => r.status === 409);
    expect(await db.doctor.findUnique({ where: { id: doctors[loser].doctor!.id } })).toMatchObject({ clinicId: null });
    await db.clinic.update({ where: { id: o.clinicId }, data: { paidDoctorCount: 3 } });
    expect((await request(app).post("/api/clinics/invites/accept").set(bearer(sign({ sub: doctors[loser].id, role: "DOCTOR" }))).send({ token: tokens[loser] })).status).toBe(200);
  });
  it("rejects a wrong account, expired and revoked invitations, and allows a dual-profile doctor", async () => {
    const o = await owner(false);
    const u = await db.user.create({ data: { email: email(), passwordHash: "unchanged", role: "PATIENT", patient: { create: { firstName: "مريض", lastName: "اختبار" } }, doctor: { create: { ...doctorProfile(), ...location } } }, include: { doctor: true } });
    const token = await invite(o.token, u.email);
    expect((await request(app).post("/api/clinics/invites/accept").set(bearer(o.token)).send({ token })).status).toBe(403);
    const auth = bearer(sign({ sub: u.id, role: "DOCTOR" }));
    await db.clinicDoctorInvite.updateMany({ where: { clinicId: o.clinicId, email: u.email }, data: { expiresAt: new Date(Date.now() - 1000) } });
    expect((await request(app).post("/api/clinics/invites/accept").set(auth).send({ token })).status).toBe(400);
    await db.clinicDoctorInvite.updateMany({ where: { clinicId: o.clinicId, email: u.email }, data: { expiresAt: new Date(Date.now() + 86400000), status: "REVOKED" } });
    expect((await request(app).post("/api/clinics/invites/accept").set(auth).send({ token })).status).toBe(400);
    const fresh = await invite(o.token, u.email);
    expect((await request(app).post("/api/clinics/invites/accept").set(auth).send({ token: fresh })).status).toBe(200);
    expect(await db.user.findUnique({ where: { id: u.id } })).toMatchObject({ role: "PATIENT", passwordHash: "unchanged" });
    expect(await db.patient.count({ where: { userId: u.id } })).toBe(1);
  });
  it("creating an owned clinic preserves an existing doctor's subscription until approval and rejection", async () => {
    const u = await db.user.create({ data: { email: email(), passwordHash: "unused-test-only", role: "DOCTOR", doctor: { create: { ...doctorProfile(), ...location, subscriptionStatus: "ACTIVE", subscriptionExpiresAt: new Date(Date.now() + 86400000) } } }, include: { doctor: true } });
    const token = sign({ sub: u.id, role: "DOCTOR" }); owners.push(u.id);
    const created = await request(app).post("/api/clinics/mine").set(bearer(token)).send(clinicProfile());
    expect(created.status).toBe(201);
    expect(await db.doctor.findUnique({ where: { id: u.doctor!.id } })).toMatchObject({ clinicId: null, subscriptionStatus: "ACTIVE" });
    const mine = await request(app).get("/api/clinics/transfers/mine").set(bearer(token));
    expect(mine.status).toBe(200); expect(mine.body.data[0].status).toBe("PENDING");
    const pendingId = mine.body.data[0].id;
    expect((await request(app).get("/api/clinics/admin/transfers").set(bearer(token))).status).toBe(403);
    expect((await request(app).patch(`/api/clinics/admin/transfers/${pendingId}`).set(bearer(adminToken)).send({ approve: false })).status).toBe(200);
    expect(await db.doctor.findUnique({ where: { id: u.doctor!.id } })).toMatchObject({ clinicId: null, subscriptionStatus: "ACTIVE" });
    expect(await db.clinicTransferRequest.findUnique({ where: { id: pendingId } })).toMatchObject({ status: "REVOKED", pendingDoctorId: null });
  });
  it("accepts direct transfer requests but never approves beyond paid capacity under concurrency", async () => {
    const o = await owner();
    await request(app).patch(`/api/clinics/admin/${o.clinicId}`).set(bearer(adminToken)).send({ verificationStatus: "VERIFIED", subscriptionStatus: "ACTIVE", paidDoctorCount: 2, subscriptionExpiresAt: new Date(Date.now() + 86400000) });
    const pending: string[] = [];
    for (let i = 0; i < 2; i++) {
      const u = await db.user.create({ data: { email: email(), passwordHash: "unused-test-only", role: "DOCTOR", doctor: { create: { ...doctorProfile(), ...location, subscriptionStatus: "ACTIVE" } } } });
      const doctorToken = sign({ sub: u.id, role: "DOCTOR" });
      const result = await request(app).post("/api/clinics/transfers").set(bearer(doctorToken)).send({ clinicId: o.clinicId });
      expect(result.status).toBe(201); pending.push(result.body.data.id);
      expect((await request(app).post("/api/clinics/transfers").set(bearer(doctorToken)).send({ clinicId: o.clinicId })).status).toBe(409);
    }
    const results = await Promise.all(pending.map(id => request(app).patch(`/api/clinics/admin/transfers/${id}`).set(bearer(adminToken)).send({ approve: true })));
    expect(results.map(r => r.status).sort()).toEqual([200, 409]);
    expect(await db.doctor.count({ where: { clinicId: o.clinicId } })).toBe(2);
    expect(await db.clinicTransferRequest.count({ where: { clinicId: o.clinicId, status: "PENDING" } })).toBe(1);
  });
  it("limits clinic managers to owner-granted permissions and revokes live sessions", async () => {
    const o = await owner();
    const joined = await accept(await invite(o.token));
    expect(joined.status).toBe(201);
    const doctor = joined.body.data.user.doctor;
    const headers = bearer(joined.body.data.accessToken);
    const managerUrl = `/api/clinics/mine/doctors/${doctor.id}/manager`;
    const invariants = await db.doctor.findUniqueOrThrow({ where: { id: doctor.id }, select: { userId: true, subscriptionStatus: true, subscriptionExpiresAt: true } });
    expect((await request(app).get("/api/clinics/mine").set(headers)).status).toBe(404);
    expect((await request(app).patch(managerUrl).set(headers).send({ isManager: true, permissions: ["VIEW_FINANCE"] })).status).toBe(404);
    expect((await request(app).patch(managerUrl).set(bearer(o.token)).send({ isManager: true, permissions: ["VIEW_FINANCE"] })).status).toBe(200);
    expect((await request(app).get("/api/clinics/mine").set(headers)).body.data).toMatchObject({ isOwner: false, permissions: ["VIEW_FINANCE"], invites: [] });
    expect((await request(app).get("/api/clinics/mine/finance").set(headers)).status).toBe(200);
    expect((await request(app).patch(`/api/clinics/mine/doctors/${doctor.id}/terms`).set(headers).send({ appointmentPriceDzd: 5000 })).status).toBe(403);
    expect((await request(app).patch("/api/clinics/mine").set(headers).send(clinicProfile())).status).toBe(403);
    expect((await request(app).post("/api/clinics/mine/invites").set(headers).send({ email: email() })).status).toBe(403);
    expect((await request(app).post("/api/clinics/mine/assistants").set(headers).send({ email: email(), allDoctors: true })).status).toBe(403);
    expect((await request(app).post(`/api/clinics/mine/doctors/${doctor.id}/assistants`).set(headers).send({ email: email() })).status).toBe(403);
    expect((await request(app).post("/api/doctor/assistants/invite").set(headers).send({ email: email() })).status).toBe(403);
    expect((await request(app).patch(managerUrl).set(headers).send({ isManager: true, permissions: ["MANAGE_TERMS"] })).status).toBe(403);
    expect((await request(app).patch(managerUrl).set(bearer(o.token)).send({ isManager: true, permissions: ["MANAGE_TERMS", "EDIT_PROFILE", "MANAGE_ASSISTANT_STATUS"] })).status).toBe(200);
    expect((await request(app).get("/api/clinics/mine/finance").set(headers)).status).toBe(403);
    expect((await request(app).patch(`/api/clinics/mine/doctors/${doctor.id}/terms`).set(headers).send({ appointmentPriceDzd: 5000 })).status).toBe(200);
    expect((await request(app).patch("/api/clinics/mine").set(headers).send(clinicProfile())).status).toBe(200);
    const other = await owner();
    expect((await request(app).patch(`/api/clinics/mine/doctors/${other.user.doctor.id}/manager`).set(bearer(o.token)).send({ isManager: true })).status).toBe(404);
    expect((await request(app).patch(managerUrl).set(bearer(o.token)).send({ isManager: false })).status).toBe(200);
    expect((await request(app).get("/api/clinics/mine").set(headers)).status).toBe(404);
    expect(await db.doctor.findUniqueOrThrow({ where: { id: doctor.id }, select: { userId: true, subscriptionStatus: true, subscriptionExpiresAt: true } })).toEqual(invariants);
    expect((await request(app).patch(managerUrl).set(bearer(o.token)).send({ isManager: true, permissions: ["VIEW_FINANCE"] })).status).toBe(200);
    await db.doctor.update({ where: { id: doctor.id }, data: { clinicId: other.clinicId } });
    expect((await request(app).get("/api/clinics/mine").set(headers)).status).toBe(404);
  });
  it("creates multiple assistants with exact owner-assigned scopes and rejects cross-clinic grants", async () => {
    const o = await owner(); const firstId = o.user.doctor.id;
    const joined = await accept(await invite(o.token)); const secondId = joined.body.data.user.doctor.id;
    const outsider = await owner();
    const create = (scope: object) => request(app).post("/api/clinics/mine/assistants").set(bearer(o.token)).send({ email: email(), ...scope });
    expect((await create({ allDoctors: false, doctorIds: [] })).status).toBe(400);
    expect((await create({ allDoctors: false, doctorIds: [outsider.user.doctor.id] })).status).toBe(400);
    const invitation = await create({ allDoctors: false, doctorIds: [secondId] });
    expect(invitation.status).toBe(200);
    const accepted = await request(app).post("/api/auth/register/assistant").send({ token: invitation.body.data.rawToken, password: "ClinicTest123!", firstName: "مساعد", lastName: "مخصص" });
    expect(accepted.status).toBe(201);
    const assistantId = accepted.body.data.user.assistant.id;
    const headers = bearer(accepted.body.data.accessToken);
    const doctorIds = async () => (await request(app).get("/api/assistant/doctors").set(headers)).body.data.map((d: { id: string }) => d.id).sort();
    expect(await doctorIds()).toEqual([secondId]);
    expect((await request(app).get("/api/auth/me").set(headers)).body.data.assistant.doctor.id).toBe(secondId);
    expect((await request(app).get("/api/appointments/queue").set({ ...headers, "X-Assistant-Doctor-Id": firstId })).status).toBe(403);
    expect((await request(app).get("/api/appointments/queue").set({ ...headers, "X-Assistant-Doctor-Id": secondId })).status).toBe(200);
    const management = (await request(app).get("/api/clinics/mine").set(bearer(o.token))).body.data;
    expect(management.assistants).toHaveLength(1);
    expect(management.doctors.find((d: { id: string }) => d.id === firstId).assistants).toHaveLength(0);
    expect(management.doctors.find((d: { id: string }) => d.id === secondId).assistants).toHaveLength(1);
    // Reusing an email through the compatibility endpoint preserves the restriction.
    expect((await request(app).post(`/api/clinics/mine/doctors/${firstId}/assistants`).set(bearer(o.token)).send({ email: accepted.body.data.user.email })).status).toBe(200);
    expect(await doctorIds()).toEqual([secondId]);
    const scopeUrl = `/api/clinics/mine/assistants/${assistantId}/scope`;
    expect((await request(app).patch(scopeUrl).set(bearer(outsider.token)).send({ allDoctors: true })).status).toBe(404);
    expect((await request(app).patch(scopeUrl).set(bearer(o.token)).send({ allDoctors: false, doctorIds: [outsider.user.doctor.id] })).status).toBe(400);
    expect((await request(app).patch(scopeUrl).set(bearer(o.token)).send({ allDoctors: true })).status).toBe(200);
    expect(await doctorIds()).toEqual([firstId, secondId].sort());
    const general = await create({ allDoctors: true });
    const secondAssistant = await request(app).post("/api/auth/register/assistant").send({ token: general.body.data.rawToken, password: "ClinicTest123!", firstName: "مساعد", lastName: "عام" });
    expect(secondAssistant.status).toBe(201);
    expect(await db.assistant.count({ where: { clinicId: o.clinicId } })).toBe(2);
    expect((await request(app).patch(scopeUrl).set(bearer(o.token)).send({ allDoctors: false, doctorIds: [secondId] })).status).toBe(200);
    await db.doctor.update({ where: { id: secondId }, data: { clinicId: outsider.clinicId } });
    expect(await doctorIds()).toEqual([]);
    expect((await request(app).get("/api/appointments/queue").set(headers)).status).toBe(403);
  });
  it("shows simultaneous doctor calls on one assistant board and revokes assignment immediately", async () => {
    const o = await owner();
    const joined = await accept(await invite(o.token));
    const firstId = o.user.doctor.id; const secondId = joined.body.data.user.doctor.id;
    const invitation = await request(app).post("/api/clinics/mine/assistants").set(bearer(o.token)).send({ email: email(), allDoctors: true });
    const accepted = await request(app).post("/api/auth/register/assistant").send({ token: invitation.body.data.rawToken, password: "ClinicTest123!", firstName: "استقبال", lastName: "موحد" });
    expect(accepted.status).toBe(201);
    const headers = bearer(accepted.body.data.accessToken);
    const today = new Date(Date.now() + 3600000).toISOString().slice(0, 10);
    const createWaiting = (doctorId: string, name: string) => db.appointment.create({ data: { doctorId, date: new Date(today + "T00:00:00Z"), startTime: "23:00", endTime: "23:15", status: "CONFIRMED", type: "IN_PERSON", guestFirstName: name, guestLastName: "اختبار", guestPhone: "0550000000" } });
    await db.doctor.updateMany({where:{id:{in:[firstId,secondId]}},data:{dutyEndsAt:new Date(Date.now()+3600000)}});
    await db.assistant.update({where:{id:accepted.body.data.user.assistant.id},data:{shiftEndsAt:new Date(Date.now()+3600000)}});
    const [first, second] = await Promise.all([createWaiting(firstId, "مريض الأول"), createWaiting(secondId, "مريض الثاني")]);
    const board = () => request(app).get("/api/assistant/queues").set({ ...headers, "X-Assistant-Doctor-Id": "stale-foreign-selection" });
    expect((await board()).body.data.every((row: { queue: { current: unknown } }) => row.queue.current === null)).toBe(true);
    expect((await request(app).post(`/api/appointments/${second.id}/arrived`).set({ ...headers, "X-Assistant-Doctor-Id": secondId })).status).toBe(200);
    expect((await request(app).post(`/api/appointments/${first.id}/arrived`).set({ ...headers, "X-Assistant-Doctor-Id": firstId })).status).toBe(200);
    const called = await Promise.all([
      request(app).post("/api/appointments/queue/next").set(bearer(sign({ sub: o.user.id, role: "DOCTOR" }))),
      request(app).post("/api/appointments/queue/next").set(bearer(joined.body.data.accessToken)),
    ]);
    expect(called.map(response => response.status)).toEqual([200, 200]);
    expect(called.every(r=>r.body.data.awaitingAssistant===true && !r.body.data.id)).toBe(true);
    for(const a of [first,second]) expect((await request(app).post(`/api/appointments/${a.id}/call`).set({...headers,"X-Assistant-Doctor-Id":a.doctorId})).status).toBe(200);
    const response = await board(); expect(response.status).toBe(200);
    expect(response.body.data.map((row: { queue: { current: { id: string } } }) => row.queue.current.id).sort()).toEqual([first.id, second.id].sort());
    const all = await request(app).get(`/api/assistant/appointments?date=${today}`).set(headers);
    expect(all.status).toBe(200); expect(all.body.data.map((row: { id: string }) => row.id).sort()).toEqual([first.id, second.id].sort());
    expect((await request(app).get("/api/assistant/queues").set(bearer(o.token))).status).toBe(403);
    expect((await request(app).get("/api/assistant/appointments?date=2026-02-30").set(headers)).status).toBe(400);
    await db.assistant.update({ where: { id: accepted.body.data.user.assistant.id }, data: { allDoctors: false, allowedDoctorIds: [firstId] } });
    expect((await board()).body.data.map((row: { doctor: { id: string } }) => row.doctor.id)).toEqual([firstId]);
    expect((await request(app).get(`/api/assistant/appointments?date=${today}`).set(headers)).body.data.map((row: { id: string }) => row.id)).toEqual([first.id]);
    expect((await request(app).post(`/api/appointments/${second.id}/arrived`).set({ ...headers, "X-Assistant-Doctor-Id": secondId })).status).toBe(403);
    await db.appointment.deleteMany({ where: { id: { in: [first.id, second.id] } } });
  });
  it("assigns clinic assistants to the selected doctor without leaking billing", async () => {
    const o = await owner(); const id = o.user.doctor.id;
    const invited = await request(app).post(`/api/clinics/mine/doctors/${id}/assistants`).set(bearer(o.token)).send({ email: email() });
    expect(invited.status).toBe(200); expect(invited.body.data.invite.tokenHash).toBeUndefined();
    const accepted = await request(app).post("/api/auth/register/assistant").send({ token: invited.body.data.rawToken, password: "ClinicTest123!", firstName: "مساعد", lastName: "الاختبار" });
    expect(accepted.status).toBe(201); expect(accepted.body.data.user.assistant.doctor.subscriptionStatus).toBeUndefined();
    const assistantId = accepted.body.data.user.assistant.id;
    expect(accepted.body.data.user.assistant.clinicId).toBe(o.clinicId);
    const colleague = await accept(await invite(o.token));
    expect(colleague.status).toBe(201);
    const colleagueId = colleague.body.data.user.doctor.id;
    const assistantHeaders = bearer(accepted.body.data.accessToken);
    const selectionHeaders = { ...assistantHeaders, "X-Assistant-Doctor-Id": colleagueId };
    const repeated = await request(app).post(`/api/clinics/mine/doctors/${colleagueId}/assistants`).set(bearer(o.token)).send({ email: accepted.body.data.user.email.toUpperCase() });
    expect(repeated.status).toBe(200);
    expect(repeated.body.data.alreadyShared).toBe(true);
    expect(repeated.body.data.assistant.id).toBe(assistantId);
    expect(repeated.body.data.rawToken).toBeUndefined();
    expect(await db.assistant.count({ where: { clinicId: o.clinicId } })).toBe(1);
    const managed = await request(app).get("/api/clinics/mine").set(bearer(o.token));
    expect(managed.status).toBe(200);
    expect(managed.body.data.doctors.every((d: { assistants: { id: string }[] }) => d.assistants.some(a => a.id === assistantId))).toBe(true);
    expect((await request(app).patch(`/api/clinics/mine/doctors/${colleagueId}/assistants/${assistantId}`).set(bearer(o.token)).send({ isActive: false })).status).toBe(200);
    expect((await request(app).get("/api/appointments/queue").set(assistantHeaders)).status).toBe(403);
    expect((await request(app).patch(`/api/clinics/mine/doctors/${colleagueId}/assistants/${assistantId}`).set(bearer(o.token)).send({ isActive: true })).status).toBe(200);
    const list = await request(app).get("/api/assistant/doctors").set(assistantHeaders);
    expect(list.status).toBe(200);
    expect(list.body.data.map((d: { id: string }) => d.id).sort()).toEqual([id, colleagueId].sort());
    expect(list.body.data[0].subscriptionStatus).toBeUndefined();
    expect((await request(app).get("/api/appointments/queue").set(selectionHeaders)).status).toBe(200);
    const me = await request(app).get("/api/auth/me").set(selectionHeaders);
    expect(me.status).toBe(200);
    expect(me.body.data.assistant.doctor.id).toBe(colleagueId);
    expect(me.body.data.assistant.doctor.consultationFee).toBeUndefined();
    await db.doctor.update({ where: { id: colleagueId }, data: { clinicId: null } });
    expect((await request(app).get("/api/appointments/queue").set(selectionHeaders)).status).toBe(403);
    expect((await request(app).patch(`/api/clinics/mine/doctors/${id}/assistants/${assistantId}`).set(bearer(o.token)).send({ isActive: false })).status).toBe(200);
    const token = accepted.body.data.accessToken;
    expect((await request(app).get("/api/appointments/queue").set(bearer(token))).status).toBe(403);
  });
});

