import { FormEvent,useState } from 'react';
import { useQuery,useQueryClient } from '@tanstack/react-query';
import { api,apiErrorMessage } from '../../lib/api';
import { Input,Select } from '../../components/ui/Input';
import { Button } from '../../components/ui/Button';
import { Pagination } from '../../components/ui/Pagination';
import { Spinner,EmptyState,ErrorState } from '../../components/ui/States';
import { AdminResults,AdminActions } from '../../components/admin/AdminUI';
import { useAdminConfirm } from '../../components/admin/AdminConfirm';
import { useAdminListParams } from '../../hooks/useAdminListParams';
import { useToast } from '../../components/ui/Toast';
type Clinic={id:string;nameAr:string;address:string;owner:{email:string};verificationStatus:string;subscriptionStatus:string;subscriptionExpiresAt:string|null;paidDoctorCount:number;_count:{doctors:number};monthlyTotal:number;doctorPrice:number;billedDoctorCount:number;discountedDoctorCount:number;referralDiscountUntil:string|null;pendingReferralDays:number;doctors:{id:string;firstName:string;lastName:string}[];revision:string};
const verification:Record<string,string>={PENDING:'قيد المراجعة',VERIFIED:'موثّقة',REJECTED:'مرفوضة'},subscription:Record<string,string>={UNPAID:'غير مفعّل',ACTIVE:'نشط',EXPIRED:'منتهي'};
export default function AdminClinics(){
 const qc=useQueryClient(),{showToast}=useToast(),confirmation=useAdminConfirm(),{params,q,setQ,search,page,setPage,update,clear}=useAdminListParams(),[formError,setFormError]=useState<{id:string;message:string}|null>(null);
 const id=params.get('id'),verificationStatus=params.get('verificationStatus')??'',subscriptionStatus=params.get('subscriptionStatus')??'';
 const query=useQuery({queryKey:['admin-clinics',search,page,id,verificationStatus,subscriptionStatus],queryFn:async({signal})=>(await api.get('/clinics/admin/list',{signal,params:{page,q:search||undefined,id:id||undefined,verificationStatus:verificationStatus||undefined,subscriptionStatus:subscriptionStatus||undefined}})).data.data as {items:Clinic[];total:number;page:number;totalPages:number}});
 const transfers=useQuery({queryKey:['admin-clinic-transfers'],queryFn:async()=>(await api.get('/clinics/admin/transfers')).data.data as {id:string;clinic:{nameAr:string};doctor:{firstName:string;lastName:string;user:{email:string}}}[]});
 function review(r:any,approve:boolean){confirmation.ask({title:approve?'الموافقة على الانتقال':'رفض طلب الانتقال',record:'د. '+r.doctor.firstName+' '+r.doctor.lastName+' — '+r.clinic.nameAr,impact:approve?'ينقل الطبيب إلى اشتراك العيادة بعد تحقق الخادم من موافقة المالك والتوثيق والسعة.':'يرفض الطلب ويحتفظ بحساب الطبيب واشتراكه الحالي.',action:async()=>{await api.patch('/clinics/admin/transfers/'+r.id,{approve});showToast(approve?'تمت الموافقة ونقل الطبيب.':'رُفض الطلب.','success');await Promise.all([qc.invalidateQueries({queryKey:['admin-clinics']}),qc.invalidateQueries({queryKey:['admin-clinic-transfers']})]);}});}
 function preview(e:FormEvent<HTMLFormElement>,c:Clinic){e.preventDefault();const f=new FormData(e.currentTarget),count=Number(f.get('paidDoctorCount')),expires=String(f.get('expires')??''),status=String(f.get('subscriptionStatus')),verificationStatus=String(f.get('verificationStatus'));if(!Number.isInteger(count)||count<0||count>1000||(status==='ACTIVE'&&(count<c._count.doctors||count<1||!expires||new Date(expires+'T23:59:59.999Z')<=new Date()))){setFormError({id:c.id,message:'الاشتراك النشط يتطلب سعة تشمل الأطباء الحاليين وتاريخ انتهاء مستقبليًا. القيم السالبة أو غير الصحيحة غير مقبولة.'});return;}setFormError(null);confirmation.ask({title:'مراجعة تغييرات العيادة',record:c.nameAr,impact:`مراجعة العيادة: ${verification[c.verificationStatus]} ← ${verification[verificationStatus]}. الاشتراك: ${subscription[c.subscriptionStatus]} ← ${subscription[status]}. السعة المدفوعة: ${c.paidDoctorCount} ← ${count}. الانتهاء: ${c.subscriptionExpiresAt?.slice(0,10)??'غير محدد'} ← ${expires||'غير محدد'}. عدد الأطباء الحاليين ${c._count.doctors}. التفعيل يتطلب تحققًا يدويًا من الدفع؛ لا يُسجل تحصيل تلقائي.`,confirmText:'حفظ التغييرات بعد المراجعة',action:async()=>{await api.patch('/clinics/admin/'+c.id,{verificationStatus,subscriptionStatus:status,paidDoctorCount:count,subscriptionExpiresAt:expires?expires+'T23:59:59.999Z':null,expectedSnapshot:c.revision});showToast('تم حفظ مراجعة العيادة واشتراكها.','success');await qc.invalidateQueries({queryKey:['admin-clinics']});}});}
 const filtered=!!(q||id||verificationStatus||subscriptionStatus);
 return <section className="space-y-5"><h1 className="text-2xl font-extrabold">العيادات والاشتراكات</h1><p className="text-sm text-slate-600">راجع توثيق العيادة منفصلًا عن الاشتراك. التفعيل يتطلب التحقق اليدوي من الدفع.</p><div className="grid gap-3 sm:grid-cols-3"><Input label="بحث عن عيادة أو مالك" value={q} onChange={e=>setQ(e.target.value)}/><Select label="مراجعة العيادة" value={verificationStatus} onChange={e=>update('verificationStatus',e.target.value)}><option value="">كل الحالات</option>{Object.entries(verification).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Select><Select label="اشتراك العيادة" value={subscriptionStatus} onChange={e=>update('subscriptionStatus',e.target.value)}><option value="">كل الاشتراكات</option>{Object.entries(subscription).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Select></div>
 <details className="card p-4"><summary className="cursor-pointer font-bold">طلبات انتقال الأطباء المسجّلين ({transfers.data?.length??'—'})</summary><div className="mt-3 space-y-3">{transfers.isLoading?<Spinner/>:transfers.isError?<ErrorState message={apiErrorMessage(transfers.error)} onRetry={()=>void transfers.refetch()}/>:transfers.data?.length?transfers.data.map(r=><article key={r.id} className="space-y-2 border-t pt-3"><p>د. {r.doctor.firstName} {r.doctor.lastName} ← {r.clinic.nameAr}</p><p><bdi dir="ltr">{r.doctor.user.email}</bdi></p><AdminActions label={'طلب انتقال '+r.doctor.firstName+' '+r.doctor.lastName}><Button onClick={()=>review(r,true)}>الموافقة على الانتقال</Button><Button variant="danger" onClick={()=>review(r,false)}>رفض الطلب</Button></AdminActions></article>):<EmptyState title="لا توجد طلبات معلّقة"/>}</div></details>
 <AdminResults total={query.data?.total} filtered={filtered} onClear={clear}/>{query.isLoading?<Spinner/>:query.isError?<ErrorState message={apiErrorMessage(query.error)} onRetry={()=>void query.refetch()}/>:query.data?.items.length?<>{query.data.items.map(c=><form key={`${c.id}-${c.revision}`} onSubmit={e=>preview(e,c)} className="card space-y-4 p-5"><header><h2 className="text-lg font-bold">{c.nameAr}</h2><p className="text-sm text-slate-600">{c.address}</p><p className="text-sm"><bdi dir="ltr">{c.owner.email}</bdi></p></header><div className="flex flex-wrap gap-2"><span className="badge bg-slate-100">المراجعة: {verification[c.verificationStatus]}</span><span className="badge bg-slate-100">الاشتراك: {subscription[c.subscriptionStatus]}</span></div><p>الأطباء الحاليون: {c._count.doctors} · السعة المشمولة بالدفع: {c.paidDoctorCount}</p><p className="text-sm">{(c.doctors??[]).map(d=>'د. '+d.firstName+' '+d.lastName).join('، ')}</p><p className="text-sm">أساس المبلغ الشهري: {c.billedDoctorCount} طبيب × {c.doctorPrice.toLocaleString('ar-DZ')} دج = <b>{c.monthlyTotal.toLocaleString('ar-DZ')} دج</b>. يُحسب على الأطباء الحاليين بعد خصم الإحالة، وليس على السعة المحجوزة.</p><p className="text-sm text-slate-600">المبلغ تقدير شهري وليس إثبات تحصيل. انتهاء التغطية المسجل: {c.subscriptionExpiresAt?new Date(c.subscriptionExpiresAt).toLocaleDateString('ar-DZ'):'غير محدد'}؛ تاريخ بداية الفترة المدفوعة غير متاح في هذا السجل.</p>{c.discountedDoctorCount>0&&<p className="text-emerald-700">خصم الإحالة يشمل {c.discountedDoctorCount} طبيب حتى {c.referralDiscountUntil?new Date(c.referralDiscountUntil).toLocaleDateString('ar-DZ'):'—'}.</p>}{c.pendingReferralDays>0&&<p>خصم محفوظ لمدة {c.pendingReferralDays} يومًا يبدأ عند تفعيل الاشتراك.</p>}
 <section className="space-y-3 border-t pt-3"><h3 className="font-bold">قرار مراجعة العيادة</h3><Select name="verificationStatus" label="قرار التوثيق" defaultValue={c.verificationStatus}>{Object.entries(verification).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Select></section><section className="space-y-3 border-t pt-3"><h3 className="font-bold">تعديل الاشتراك بعد التحقق من الدفع</h3><div className="grid gap-3 sm:grid-cols-2"><Select name="subscriptionStatus" label="حالة الاشتراك" defaultValue={c.subscriptionStatus}>{Object.entries(subscription).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Select><Input name="paidDoctorCount" label="عدد الأطباء المشمولين بالدفع" type="number" min={0} max={1000} defaultValue={c.paidDoctorCount} required/><Input name="expires" label="تاريخ انتهاء الاشتراك" type="date" defaultValue={c.subscriptionExpiresAt?.slice(0,10)??''}/></div></section>{formError?.id===c.id&&<p role="alert" className="text-red-700">{formError.message}</p>}<Button type="submit">مراجعة التغييرات قبل الحفظ</Button></form>)}<Pagination page={query.data.page} totalPages={query.data.totalPages} onChange={setPage}/></>:<EmptyState title={filtered?'لا نتائج مطابقة':'لا توجد عيادات'}/>} {confirmation.dialog}</section>;
}
